### ISSUE TITLE
 How to save a trained model

### ISSUE THREAD

**Issue by wxzwxz131** [ymirsky/KitNET-py#3]
When the  model is trained, how to save it for next prediction

**Comment by ymirsky** [comment]
You would need to implement a save and load method in the KitNET class. The easiest way is to perform np.save(...) on each internal variable (self.*) and load the same values in after. A cleaner way would be to have the save and load functions store the variables into a dict and then save just the dict to disk.

You should know that you'll also need to save the FM variables if training is incomplete.
